"""Rich streaming output for code agent.

Provides async streaming interfaces for real-time agent progress display,
including token deltas, tool calls, step progress, plan updates, and
code execution events.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

import structlog

from app.engine.planning import Plan

logger = structlog.get_logger()


class StreamOutput(ABC):
    """Abstract interface for streaming agent output.

    Implementations can render to console, WebSocket, HTTP SSE, or any
    other streaming protocol.
    """

    @abstractmethod
    async def on_token(self, token: str) -> None:
        """Called when a token is generated by the model."""
        ...

    @abstractmethod
    async def on_tool_call(self, tool_name: str, arguments: dict) -> None:
        """Called when a tool is invoked."""
        ...

    @abstractmethod
    async def on_tool_result(self, tool_name: str, result: Any) -> None:
        """Called when a tool returns a result."""
        ...

    @abstractmethod
    async def on_step_start(self, step: int, description: str = "") -> None:
        """Called when a new step begins."""
        ...

    @abstractmethod
    async def on_step_end(self, step: int, result: Any) -> None:
        """Called when a step completes."""
        ...

    @abstractmethod
    async def on_plan_update(self, plan: Plan) -> None:
        """Called when the plan is updated."""
        ...

    @abstractmethod
    async def on_code_execution(self, code: str, output: str, error: str | None = None) -> None:
        """Called after code execution completes."""
        ...

    @abstractmethod
    async def on_thinking(self, thought: str) -> None:
        """Called when the agent produces thinking/reasoning text."""
        ...

    @abstractmethod
    async def on_final_answer(self, answer: str) -> None:
        """Called when the agent produces the final answer."""
        ...

    @abstractmethod
    async def on_error(self, error: str) -> None:
        """Called when an error occurs."""
        ...


class DefaultStreamOutput(StreamOutput):
    """Default stream output that logs to structlog."""

    def __init__(self, session_id: str = ""):
        self.session_id = session_id

    async def on_token(self, token: str) -> None:
        logger.debug("stream.token", session=self.session_id, token=token)

    async def on_tool_call(self, tool_name: str, arguments: dict) -> None:
        logger.info("stream.tool_call", session=self.session_id, tool=tool_name, arguments=arguments)

    async def on_tool_result(self, tool_name: str, result: Any) -> None:
        logger.info(
            "stream.tool_result",
            session=self.session_id,
            tool=tool_name,
            result=str(result)[:500],
        )

    async def on_step_start(self, step: int, description: str = "") -> None:
        logger.info("stream.step_start", session=self.session_id, step=step, description=description)

    async def on_step_end(self, step: int, result: Any) -> None:
        logger.info("stream.step_end", session=self.session_id, step=step, result=str(result)[:500])

    async def on_plan_update(self, plan: Plan) -> None:
        logger.info(
            "stream.plan_update",
            session=self.session_id,
            steps=len(plan.steps),
            current=plan.current_step,
        )

    async def on_code_execution(self, code: str, output: str, error: str | None = None) -> None:
        logger.info(
            "stream.code_execution",
            session=self.session_id,
            code=code[:200],
            output=output[:500],
            error=error,
        )

    async def on_thinking(self, thought: str) -> None:
        logger.debug("stream.thinking", session=self.session_id, thought=thought[:200])

    async def on_final_answer(self, answer: str) -> None:
        logger.info("stream.final_answer", session=self.session_id, answer=answer[:500])

    async def on_error(self, error: str) -> None:
        logger.error("stream.error", session=self.session_id, error=error)


class CollectingStreamOutput(StreamOutput):
    """Collects all events into a list for testing or deferred processing."""

    def __init__(self) -> None:
        self.events: list[dict[str, Any]] = []

    def _record(self, event_type: str, **kwargs) -> None:
        self.events.append({"type": event_type, **kwargs})

    async def on_token(self, token: str) -> None:
        self._record("token", token=token)

    async def on_tool_call(self, tool_name: str, arguments: dict) -> None:
        self._record("tool_call", tool_name=tool_name, arguments=arguments)

    async def on_tool_result(self, tool_name: str, result: Any) -> None:
        self._record("tool_result", tool_name=tool_name, result=result)

    async def on_step_start(self, step: int, description: str = "") -> None:
        self._record("step_start", step=step, description=description)

    async def on_step_end(self, step: int, result: Any) -> None:
        self._record("step_end", step=step, result=result)

    async def on_plan_update(self, plan: Plan) -> None:
        self._record("plan_update", plan=plan.model_dump())

    async def on_code_execution(self, code: str, output: str, error: str | None = None) -> None:
        self._record("code_execution", code=code, output=output, error=error)

    async def on_thinking(self, thought: str) -> None:
        self._record("thinking", thought=thought)

    async def on_final_answer(self, answer: str) -> None:
        self._record("final_answer", answer=answer)

    async def on_error(self, error: str) -> None:
        self._record("error", error=error)
