#!/usr/bin/env python3
"""Generator for frontend pages and components with full implementations."""

from pathlib import Path

BASE = Path("/workspace/agent-engine")
PAGES_DIR = BASE / "frontend-react" / "src" / "pages" / "extended"
COMPONENTS_DIR = BASE / "frontend-react" / "src" / "components" / "extended"

PAGES_DIR.mkdir(parents=True, exist_ok=True)
COMPONENTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_page(name: str, title: str, description: str) -> str:
    """Generate a full React page component."""
    lines = [
        '/* ' + description + ' */',
        '',
        "import React, { useState, useEffect, useCallback, useMemo } from 'react';",
        '',
        'interface Item {',
        '  id: string;',
        '  name: string;',
        '  status: string;',
        '  createdAt: string;',
        '}',
        '',
        'export default function ' + name + '() {',
        '  const [items, setItems] = useState<Item[]>([]);',
        '  const [loading, setLoading] = useState(true);',
        '  const [error, setError] = useState<string | null>(null);',
        '  const [searchQuery, setSearchQuery] = useState("");',
        '  const [statusFilter, setStatusFilter] = useState<string>("all");',
        '  const [page, setPage] = useState(1);',
        '  const [totalPages, setTotalPages] = useState(1);',
        '',
        '  const fetchData = useCallback(async () => {',
        '    try {',
        '      setLoading(true);',
        '      setError(null);',
        '      const mockData: Item[] = Array.from({ length: 10 }, (_, i) => ({',
        '        id: `item-${i}`,',
        '        name: `' + title + ' ${i}`,',
        '        status: i % 2 === 0 ? "active" : "inactive",',
        '        createdAt: new Date().toISOString(),',
        '      }));',
        '      setItems(mockData);',
        '      setTotalPages(5);',
        '    } catch (err) {',
        '      setError(err instanceof Error ? err.message : "Unknown error");',
        '    } finally {',
        '      setLoading(false);',
        '    }',
        '  }, [page, statusFilter]);',
        '',
        '  useEffect(() => {',
        '    fetchData();',
        '  }, [fetchData]);',
        '',
        '  const filteredItems = useMemo(() => {',
        '    return items.filter(item => {',
        '      const matchesSearch = item.name.toLowerCase().includes(searchQuery.toLowerCase());',
        '      const matchesStatus = statusFilter === "all" || item.status === statusFilter;',
        '      return matchesSearch && matchesStatus;',
        '    });',
        '  }, [items, searchQuery, statusFilter]);',
        '',
        '  if (loading) {',
        '    return (',
        '      <div className="flex items-center justify-center h-64">',
        '        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>',
        '      </div>',
        '    );',
        '  }',
        '',
        '  if (error) {',
        '    return (',
        '      <div className="p-6">',
        '        <div className="bg-red-50 border border-red-200 rounded-lg p-4">',
        '          <h3 className="text-red-800 font-medium">Error</h3>',
        '          <p className="text-red-600 mt-1">{error}</p>',
        '        </div>',
        '      </div>',
        '    );',
        '  }',
        '',
        '  return (',
        '    <div className="p-6 max-w-7xl mx-auto">',
        '      <div className="mb-6">',
        '        <h1 className="text-2xl font-bold text-gray-900">' + title + '</h1>',
        '        <p className="text-gray-600 mt-1">' + description + '.</p>',
        '      </div>',
        '',
        '      <div className="mb-4 flex gap-4">',
        '        <input',
        '          type="text"',
        '          placeholder="Search..."',
        '          className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"',
        '          value={searchQuery}',
        '          onChange={(e) => setSearchQuery(e.target.value)}',
        '        />',
        '        <select',
        '          className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"',
        '          value={statusFilter}',
        '          onChange={(e) => setStatusFilter(e.target.value)}',
        '        >',
        '          <option value="all">All Status</option>',
        '          <option value="active">Active</option>',
        '          <option value="inactive">Inactive</option>',
        '        </select>',
        '      </div>',
        '',
        '      <div className="bg-white shadow rounded-lg overflow-hidden">',
        '        <table className="min-w-full divide-y divide-gray-200">',
        '          <thead className="bg-gray-50">',
        '            <tr>',
        '              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>',
        '              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>',
        '              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Created</th>',
        '              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>',
        '            </tr>',
        '          </thead>',
        '          <tbody className="bg-white divide-y divide-gray-200">',
        '            {filteredItems.map((item) => (',
        '              <tr key={item.id} className="hover:bg-gray-50">',
        '                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.name}</td>',
        '                <td className="px-6 py-4 whitespace-nowrap">',
        '                  <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${item.status === "active" ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-800"}`}>',
        '                    {item.status}',
        '                  </span>',
        '                </td>',
        '                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">',
        '                  {new Date(item.createdAt).toLocaleDateString()}',
        '                </td>',
        '                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">',
        '                  <button className="text-blue-600 hover:text-blue-900 mr-3">Edit</button>',
        '                  <button className="text-red-600 hover:text-red-900">Delete</button>',
        '                </td>',
        '              </tr>',
        '            ))}',
        '          </tbody>',
        '        </table>',
        '      </div>',
        '',
        '      <div className="mt-4 flex justify-between items-center">',
        '        <span className="text-sm text-gray-700">',
        '          Page {page} of {totalPages}',
        '        </span>',
        '        <div className="flex gap-2">',
        '          <button',
        '            disabled={page <= 1}',
        '            onClick={() => setPage(p => p - 1)}',
        '            className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"',
        '          >',
        '            Previous',
        '          </button>',
        '          <button',
        '            disabled={page >= totalPages}',
        '            onClick={() => setPage(p => p + 1)}',
        '            className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"',
        '          >',
        '            Next',
        '          </button>',
        '        </div>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
        '',
    ]
    return '\n'.join(lines)


def generate_component(name: str, description: str) -> str:
    """Generate a full React component."""
    lines = [
        '/* ' + description + ' */',
        '',
        "import React, { useState, useEffect, useCallback, useRef } from 'react';",
        '',
        'interface ' + name + 'Props {',
        '  /** Additional CSS class names. */',
        '  className?: string;',
        '  /** Whether the component is disabled. */',
        '  disabled?: boolean;',
        '  /** Click handler. */',
        '  onClick?: () => void;',
        '  /** Change handler. */',
        '  onChange?: (value: string) => void;',
        '  /** Child elements. */',
        '  children?: React.ReactNode;',
        '}',
        '',
        '/** ' + description + '. */',
        'export default function ' + name + '(props: ' + name + 'Props) {',
        '  const { className = "", disabled = false, onClick, onChange, children } = props;',
        '  const [value, setValue] = useState("");',
        '  const [focused, setFocused] = useState(false);',
        '  const inputRef = useRef<HTMLInputElement>(null);',
        '',
        '  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {',
        '    setValue(e.target.value);',
        '    onChange?.(e.target.value);',
        '  }, [onChange]);',
        '',
        '  const handleClick = useCallback(() => {',
        '    if (!disabled) {',
        '      onClick?.();',
        '    }',
        '  }, [disabled, onClick]);',
        '',
        '  const handleFocus = useCallback(() => {',
        '    setFocused(true);',
        '  }, []);',
        '',
        '  const handleBlur = useCallback(() => {',
        '    setFocused(false);',
        '  }, []);',
        '',
        '  useEffect(() => {',
        '    if (focused && inputRef.current) {',
        '      inputRef.current.focus();',
        '    }',
        '  }, [focused]);',
        '',
        '  return (',
        '    <div',
        '      className={`${className} ${disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}',
        '      onClick={handleClick}',
        '    >',
        '      <input',
        '        ref={inputRef}',
        '        type="text"',
        '        value={value}',
        '        onChange={handleChange}',
        '        onFocus={handleFocus}',
        '        onBlur={handleBlur}',
        '        disabled={disabled}',
        '        className={`w-full px-3 py-2 border rounded-md focus:ring-2 focus:ring-blue-500 ${focused ? "border-blue-500" : "border-gray-300"}`}',
        '        placeholder="Enter value..."',
        '      />',
        '      {children}',
        '    </div>',
        '  );',
        '}',
        '',
    ]
    return '\n'.join(lines)


# Page definitions
pages = [
    ("UserManagementPage", "User Management", "Manage user accounts, roles, and permissions"),
    ("UserListPage", "User Directory", "Browse and search user accounts"),
    ("UserDetailPage", "User Profile", "View detailed user information and activity"),
    ("UserCreatePage", "Create User", "Add new user accounts"),
    ("UserEditPage", "Edit User", "Modify user information and settings"),
    ("RoleManagementPage", "Role Management", "Define and manage user roles"),
    ("PermissionManagerPage", "Permissions", "Configure granular permissions"),
    ("BillingDashboardPage", "Billing Overview", "Monitor billing and subscription metrics"),
    ("SubscriptionPage", "Subscriptions", "Manage subscription plans and status"),
    ("InvoiceListPage", "Invoices", "View and download invoice records"),
    ("PaymentHistoryPage", "Payment History", "Track payment transactions"),
    ("UsageAnalyticsPage", "Usage Analytics", "Monitor resource consumption"),
    ("PlanManagementPage", "Plan Management", "Create and configure pricing plans"),
    ("NotificationCenterPage", "Notifications", "View and manage all notifications"),
    ("NotificationSettingsPage", "Notification Preferences", "Configure notification delivery settings"),
    ("EmailTemplatePage", "Email Templates", "Design and manage email templates"),
    ("WebhookManagementPage", "Webhooks", "Configure webhook endpoints and events"),
    ("AuditLogPage", "Audit Log", "Review system audit trail"),
    ("LoginHistoryPage", "Login History", "View authentication history"),
    ("SecuritySettingsPage", "Security Settings", "Configure security policies"),
    ("KnowledgeBasePage", "Knowledge Base", "Browse knowledge base articles"),
    ("DocumentUploadPage", "Upload Documents", "Upload documents to knowledge base"),
    ("DocumentViewerPage", "Document Viewer", "View document content and metadata"),
    ("SearchKnowledgePage", "Knowledge Search", "Search knowledge base content"),
    ("CollectionManagerPage", "Collections", "Manage document collections"),
    ("OrganizationPage", "Organization", "Manage organization settings"),
    ("TeamManagementPage", "Teams", "Manage teams and membership"),
    ("MemberDirectoryPage", "Directory", "Browse organization members"),
    ("InvitationPage", "Invitations", "Manage team invitations"),
    ("ModelMarketplacePage", "Model Marketplace", "Discover and compare AI models"),
    ("ModelDetailPage", "Model Details", "View model specifications and benchmarks"),
    ("ModelComparePage", "Compare Models", "Compare multiple models side by side"),
    ("BenchmarkResultsPage", "Benchmarks", "View model benchmark results"),
    ("PluginStorePage", "Plugin Store", "Browse and install plugins"),
    ("PluginDetailPage", "Plugin Details", "View plugin information and reviews"),
    ("InstalledPluginsPage", "Installed Plugins", "Manage installed plugins"),
    ("AnalyticsDashboardPage", "Analytics", "View analytics dashboards"),
    ("UserBehaviorPage", "User Behavior", "Analyze user behavior patterns"),
    ("PerformanceMonitorPage", "Performance", "Monitor system performance metrics"),
    ("BusinessMetricsPage", "Business Metrics", "Track business KPIs"),
    ("CustomReportPage", "Custom Reports", "Create and schedule custom reports"),
    ("WorkflowTemplatePage", "Workflow Templates", "Browse workflow templates"),
    ("TemplateDetailPage", "Template Details", "View template information"),
    ("TemplateEditorPage", "Template Editor", "Edit workflow templates"),
    ("IntegrationSettingsPage", "Integrations", "Manage third-party integrations"),
    ("SlackIntegrationPage", "Slack", "Configure Slack integration"),
    ("GitHubIntegrationPage", "GitHub", "Configure GitHub integration"),
    ("JiraIntegrationPage", "Jira", "Configure Jira integration"),
    ("SettingsPage", "Settings", "Application settings and configuration"),
]

# Component definitions
components = [
    ("UserTable", "Data table for displaying users"),
    ("UserForm", "Form for creating/editing users"),
    ("UserCard", "Card displaying user information"),
    ("UserSearch", "Search component for users"),
    ("UserFilter", "Filter panel for user list"),
    ("UserRoleBadge", "Badge showing user role"),
    ("UserStatusIndicator", "Status indicator for user"),
    ("UserAvatar", "Avatar component with fallback"),
    ("UserProfileCard", "Detailed user profile card"),
    ("UserActivityTimeline", "Timeline of user activities"),
    ("RoleSelector", "Dropdown for selecting roles"),
    ("PermissionMatrix", "Matrix of permissions by role"),
    ("RoleCard", "Card displaying role information"),
    ("PermissionToggle", "Toggle for enabling permissions"),
    ("BillingSummary", "Summary of billing information"),
    ("SubscriptionCard", "Card showing subscription details"),
    ("InvoiceTable", "Table of invoices"),
    ("PaymentMethodCard", "Card for payment methods"),
    ("UsageChart", "Chart showing resource usage"),
    ("PlanComparison", "Compare different plans"),
    ("PricingTable", "Pricing comparison table"),
    ("NotificationList", "List of notifications"),
    ("NotificationItem", "Single notification item"),
    ("NotificationBell", "Bell icon with unread count"),
    ("NotificationPreferences", "Preferences form for notifications"),
    ("EmailTemplateEditor", "Editor for email templates"),
    ("WebhookConfigForm", "Form for webhook configuration"),
    ("AuditLogTable", "Table of audit log entries"),
    ("AuditLogFilter", "Filter panel for audit logs"),
    ("LoginHistoryTable", "Table of login attempts"),
    ("SecurityScoreCard", "Card showing security score"),
    ("MFASetup", "MFA setup wizard"),
    ("DocumentUploader", "Drag-and-drop document uploader"),
    ("DocumentList", "List of documents"),
    ("DocumentPreview", "Preview document content"),
    ("DocumentMetadata", "Display document metadata"),
    ("SearchBar", "Search bar with suggestions"),
    ("SearchResults", "Display search results"),
    ("SearchFilters", "Filters for search results"),
    ("CollectionCard", "Card showing collection info"),
    ("CollectionTree", "Tree view of collections"),
    ("OrganizationSwitcher", "Switch between organizations"),
    ("TeamCard", "Card showing team information"),
    ("TeamMemberList", "List of team members"),
    ("InviteMemberForm", "Form to invite members"),
    ("MemberRoleEditor", "Editor for member roles"),
    ("ModelCard", "Card displaying AI model"),
    ("ModelComparisonTable", "Table comparing models"),
    ("BenchmarkChart", "Chart showing benchmarks"),
    ("ModelSearch", "Search for models"),
    ("ModelFilter", "Filter panel for models"),
    ("PluginCard", "Card displaying plugin"),
    ("PluginGrid", "Grid of plugins"),
    ("PluginReviews", "Reviews section for plugin"),
    ("PluginInstallButton", "Install/uninstall button"),
    ("PluginConfigForm", "Form for plugin configuration"),
    ("AnalyticsChart", "Chart for analytics data"),
    ("MetricsGrid", "Grid of metric cards"),
    ("DatePicker", "Date range picker"),
    ("ExportButton", "Export data button"),
    ("ReportBuilder", "Build custom reports"),
    ("ReportPreview", "Preview generated report"),
    ("FunnelChart", "Funnel visualization"),
    ("CohortTable", "Cohort analysis table"),
    ("RetentionChart", "Retention curve chart"),
    ("RealtimeChart", "Real-time updating chart"),
    ("WorkflowCanvas", "Canvas for workflow editor"),
    ("WorkflowNode", "Node in workflow editor"),
    ("WorkflowEdge", "Edge connecting nodes"),
    ("WorkflowToolbar", "Toolbar for workflow editor"),
    ("WorkflowProperties", "Properties panel"),
    ("TemplateCard", "Card showing template"),
    ("TemplatePreview", "Preview template"),
    ("TemplateVersionHistory", "Version history list"),
    ("TemplateRating", "Rating component for templates"),
    ("IntegrationCard", "Card showing integration"),
    ("IntegrationStatus", "Status indicator for integration"),
    ("SlackChannelList", "List of Slack channels"),
    ("GitHubRepoList", "List of GitHub repositories"),
    ("JiraProjectList", "List of Jira projects"),
    ("SettingsSection", "Section in settings page"),
    ("SettingsForm", "Form for settings"),
    ("ThemeSelector", "Theme selection component"),
    ("LanguageSelector", "Language selection dropdown"),
    ("ToastNotification", "Toast notification component"),
    ("ConfirmDialog", "Confirmation dialog"),
    ("Pagination", "Pagination component"),
    ("Breadcrumb", "Breadcrumb navigation"),
    ("Sidebar", "Sidebar navigation"),
    ("Header", "Page header component"),
    ("PageLoader", "Page loading indicator"),
    ("ErrorBoundary", "Error boundary component"),
    ("EmptyState", "Empty state placeholder"),
    ("SkeletonLoader", "Skeleton loading placeholder"),
    ("Tabs", "Tabbed interface component"),
    ("Accordion", "Accordion/collapse component"),
    ("Modal", "Modal dialog component"),
    ("Dropdown", "Dropdown menu component"),
    ("Tooltip", "Tooltip component"),
    ("Progress", "Progress bar component"),
    ("Badge", "Badge/label component"),
    ("Alert", "Alert notification component"),
    ("Card", "Generic card component"),
    ("Table", "Generic data table component"),
    ("Form", "Generic form component"),
    ("Input", "Form input component"),
    ("Select", "Select dropdown component"),
    ("Checkbox", "Checkbox component"),
    ("Radio", "Radio button component"),
    ("Toggle", "Toggle switch component"),
    ("TextArea", "Text area component"),
    ("ColorPicker", "Color picker component"),
    ("FileInput", "File upload input"),
    ("ImagePreview", "Image preview component"),
    ("VideoPlayer", "Video player component"),
    ("AudioPlayer", "Audio player component"),
    ("CodeEditor", "Code editor component"),
    ("MarkdownRenderer", "Markdown content renderer"),
    ("JSONViewer", "JSON tree viewer"),
]

# Generate pages
for name, title, desc in pages:
    page_code = generate_page(name, title, desc)
    (PAGES_DIR / (name + ".tsx")).write_text(page_code)

print("Generated " + str(len(pages)) + " pages")

# Generate components
for name, desc in components:
    comp_code = generate_component(name, desc)
    (COMPONENTS_DIR / (name + ".tsx")).write_text(comp_code)

print("Generated " + str(len(components)) + " components")
