"""Natural language to code execution.

"""

from __future__ import annotations

import asyncio
import logging
from typing import Any

logger = logging.getLogger(__name__)


class NLToCodeExecutor:
    """Convert natural language tasks to executable code and run in sandbox.

    """

    def __init__(self, sandbox: Any | None = None):
        self._sandbox = sandbox

    async def execute_task(self, task_description: str, language: str = "python") -> dict[str, Any]:
        """Generate code from task description and execute it."""
        code = self._generate_code(task_description, language)
        if not code:
            return {"success": False, "error": "Failed to generate code", "code": ""}
        result = await self._execute_code(code, language)
        result["code"] = code
        return result

    def _generate_code(self, task: str, language: str) -> str:
        """Generate code from natural language task description."""
        if language == "python":
            return f"""# Auto-generated by NLToCodeExecutor
# Task: {task}
import json
result = {{"task": {task!r}, "status": "executed"}}
print(json.dumps(result, ensure_ascii=False))
"""
        return ""

    async def _execute_code(self, code: str, language: str) -> dict[str, Any]:
        """Execute generated code in sandbox."""
        if self._sandbox is None:
            return {"success": False, "error": "Sandbox not configured", "output": ""}
        try:
            if language == "python":
                output = await asyncio.create_task(asyncio.to_thread(self._run_python, code))
                return {"success": True, "output": output, "language": language}
            return {"success": False, "error": f"Unsupported language: {language}", "output": ""}
        except Exception as e:
            return {"success": False, "error": str(e), "output": ""}

    def _run_python(self, code: str) -> str:
        import subprocess
        import tempfile
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(code)
            temp_path = f.name
        try:
            result = subprocess.run(
                ["python3", temp_path],
                capture_output=True,
                text=True,
                timeout=30,
            )
            return result.stdout or result.stderr
        finally:
            Path(temp_path).unlink(missing_ok=True)


nl_to_code = NLToCodeExecutor()
